"""add status column in prodinventory

Revision ID: 8f5d0799563a
Revises: d3f6140ed077
Create Date: 2024-07-05 04:18:35.453521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5d0799563a'
down_revision = 'd3f6140ed077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prod_inventory', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
