"""add is_void

Revision ID: d3f6140ed077
Revises: 
Create Date: 2024-07-04 11:42:44.759222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f6140ed077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indiv_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_void', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indiv_transaction', schema=None) as batch_op:
        batch_op.drop_column('is_void')

    # ### end Alembic commands ###
